// Import profundo: da raiz do pacote vem o barril inteiro, com milhares de
// ícones.

export { ArrowLeft as ArrowLeftIcon } from '@phosphor-icons/react/dist/icons/ArrowLeft'
export { ArrowRight as ArrowRightIcon } from '@phosphor-icons/react/dist/icons/ArrowRight'
export { ArrowUp as ArrowUpIcon } from '@phosphor-icons/react/dist/icons/ArrowUp'
export { ArrowDown as ArrowDownIcon } from '@phosphor-icons/react/dist/icons/ArrowDown'
export { ArrowsDownUp as ArrowsDownUpIcon } from '@phosphor-icons/react/dist/icons/ArrowsDownUp'
export { CaretUpDown as CaretUpDownIcon } from '@phosphor-icons/react/dist/icons/CaretUpDown'
export { Check as CheckIcon } from '@phosphor-icons/react/dist/icons/Check'
export { Circle as CircleIcon } from '@phosphor-icons/react/dist/icons/Circle'
export { Copy as CopyIcon } from '@phosphor-icons/react/dist/icons/Copy'
export { DotsSixVertical as DotsSixVerticalIcon } from '@phosphor-icons/react/dist/icons/DotsSixVertical'
export { DownloadSimple as DownloadSimpleIcon } from '@phosphor-icons/react/dist/icons/DownloadSimple'
export { FileText as FileTextIcon } from '@phosphor-icons/react/dist/icons/FileText'
export { EnvelopeSimple as EnvelopeSimpleIcon } from '@phosphor-icons/react/dist/icons/EnvelopeSimple'
export { Keyboard as KeyboardIcon } from '@phosphor-icons/react/dist/icons/Keyboard'
export { List as ListIcon } from '@phosphor-icons/react/dist/icons/List'
export { MagnifyingGlass as MagnifyingGlassIcon } from '@phosphor-icons/react/dist/icons/MagnifyingGlass'
export { Moon as MoonIcon } from '@phosphor-icons/react/dist/icons/Moon'
export { Paperclip as PaperclipIcon } from '@phosphor-icons/react/dist/icons/Paperclip'
export { Phone as PhoneIcon } from '@phosphor-icons/react/dist/icons/Phone'
export { Sun as SunIcon } from '@phosphor-icons/react/dist/icons/Sun'
export { User as UserIcon } from '@phosphor-icons/react/dist/icons/User'
export { WarningCircle as WarningCircleIcon } from '@phosphor-icons/react/dist/icons/WarningCircle'
export { X as XIcon } from '@phosphor-icons/react/dist/icons/X'
